name: Deploy to GitHub Pages

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - run: npm test
      - run: npm run build
        env:
          VITE_BASE_URL: /${{ github.event.repository.name }}/
          VITE_CIRCLECI_PROXY: ${{ secrets.VITE_CIRCLECI_PROXY }}
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist
      - uses: actions/deploy-pages@v5
        id: deployment
